# Generated by Django 2.1.7 on 2019-02-21 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_auto_20190218_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='name',
        ),
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='votes.Candidate'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
